// The other packages in this monorepo (workflows/*) re-export via single named
// re-exports, e.g. `export { featurePlanningWorkflow } from "./plan-intent"`.
// `export * from` is intentionally NOT used because it does not load under
// Node's strict ESM resolver when this file is consumed via the package's
// `exports` field. Keep this in lockstep with the other packages.

export { bakaHomeDir } from "./baka-home"
export { BUILT_IN_CATALOG } from "./built-in-catalog"
export type {
	AggregateRequest,
	AggregateResponse,
	ApiCatalog,
	ApiPackEntry,
	Catalog,
	CatalogError,
	CatalogOwner,
	PackEntry,
	PackLookupResponse,
	Tier,
	VerifiedCatalogEntry,
	VerifiedResponse,
} from "./catalog"
export {
	AggregateRequestSchema,
	AggregateResponseSchema,
	ApiCatalogSchema,
	ApiPackEntrySchema,
	CatalogErrorSchema,
	CatalogOwnerSchema,
	CatalogSchema,
	PackEntrySchema,
	PackLookupResponseSchema,
	TIER_VALUES,
	VerifiedCatalogEntrySchema,
	VerifiedResponseSchema,
} from "./catalog"
export {
	BAKA_DEFAULT_WORKER_MODEL,
	BAKA_EXIT_CODE,
	BAKA_LOCKFILE_NAME,
	BAKA_NODE_MAJOR,
	BAKA_PROJECT_PATHS,
	BAKA_USER_DIR,
	ENGINE_STATUS,
	exitCodeForRule,
	PACK_CATEGORY,
	RECIPE_ERROR_CODES,
} from "./constants"
export type { BakaCapability, CompatibilityRequest, ContractDocumentId, Handshake, Health } from "./contract"
export {
	BAKA_CAPABILITIES,
	BAKA_CONTRACT_MAJOR,
	BAKA_CONTRACT_VERSION,
	CatalogDocumentSchema,
	CONTRACT_DOCUMENT_IDS,
	CONTRACT_DOCUMENTS,
	contractJsonSchema,
	FillSchema,
	HandshakeSchema,
	HealthSchema,
	incompatibility,
	isContractDocumentId,
	PreviewSchema,
	SlotListSchema,
} from "./contract"
export type { JsonSchema } from "./json-schema"
export { paramsJsonSchema, recipeResultJsonSchema } from "./json-schema"
export type { NormalizedParams } from "./params"
export { normalizeParams } from "./params"
export type {
	RegistryArtifact,
	RegistryCatalogEntry,
	RegistryConfigMap,
	RegistryCredential,
	RegistryPackDetail,
	RegistryPreviewEntry,
	RegistryPreviewListResponse,
	RegistryPreviewState,
	RegistryRecipePreview,
	RegistryTier,
	RegistryVersionDetail,
	RegistryVersionStatus,
	RegistryVersionSummary,
	RegistryVisibility,
} from "./registry-config"
export {
	DEFAULT_REGISTRY_URL,
	normalizeRegistryUrl,
	REGISTRY_PREVIEW_STATES,
	REGISTRY_TIERS,
	REGISTRY_VERSION_STATUSES,
	REGISTRY_VISIBILITIES,
	RegistryArtifactSchema,
	RegistryCatalogEntrySchema,
	RegistryCatalogResponseSchema,
	RegistryConfigMapSchema,
	RegistryCredentialSchema,
	RegistryPackDetailSchema,
	RegistryPreviewEntrySchema,
	RegistryPreviewListResponseSchema,
	RegistryRecipePreviewSchema,
	RegistryScreeningSchema,
	RegistryVersionDetailSchema,
	RegistryVersionSummarySchema,
	resolveRegistryUrlList,
	resolveSingleRegistryUrl,
} from "./registry-config"

export {
	ApiErrorSchema,
	BakaLockSchema,
	ChangeOpSchema,
	ChangeReasonSchema,
	ChangesetEntrySchema,
	LlmCallSchema,
	OnExistingSchema,
	OpenSlotSchema,
	OrchestrationStateSchema,
	PARAM_FORMATS,
	PARAM_TYPES,
	PackManifestSchema,
	PackPinSchema,
	PackRecipeParamSchema,
	PackRecipeSchema,
	ParamTypeNodeSchema,
	paramsToZod,
	RecipeCompensationSchema,
	RecipeErrorCodeSchema,
	RecipeResultSchema,
	ResolvedPlanSchema,
	ResolvedPlanStepSchema,
	SlotDeclSchema,
	SlotFillSchema,
	SlotKindSchema,
	SlotModeSchema,
	SlotRecordSchema,
	SlotsInputSchema,
	ValidationDiagnosticSchema,
	ValidatorRunSchema,
} from "./schemas"
export type {
	AddonRunRequest,
	ApiError,
	BakaAddon,
	BakaLock,
	ChangeOp,
	ChangesetEntry,
	LLMMessage,
	LLMMessageRole,
	LLMProvider,
	LLMRequest,
	LLMResponse,
	LLMUsage,
	LlmCall,
	OnExisting,
	OpenSlot,
	OrchestrationState,
	PackManifest,
	PackPin,
	PackRecipe,
	PackRecipeParam,
	ParamFormat,
	ParamTypeNode,
	RecipeCompensation,
	RecipeContext,
	RecipeErrorCode,
	RecipeFiles,
	RecipeFileWrite,
	RecipeResult,
	RecipeStep,
	RecipeWriteOptions,
	ResolvedLLMConfig,
	ResolvedPlan,
	SlotDecl,
	SlotMode,
	SlotRecord,
	SlotsInput,
	StepContext,
	StepResponse,
	ValidationDiagnostic,
	ValidationResult,
	ValidatorRun,
	WorkflowStep,
} from "./types"
export { AgentRole } from "./types"
